name: Check dependencies for updates

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight UTC
  workflow_dispatch:

jobs:
  check-dependencies:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: diaspeiro/actions/duck@3cf8e73d555d3fbde3dfee9596be3dc479fbbd0a
